### ISSUE TITLE
How to add item click listener

### ISSUE THREAD

**Issue by DanielHerzz** [qandeelabbassi/Dropsy#1]
dropdown_fruits.onMenuItemClickListener (i, item -> {
	                ^^^^^^^^^^^^^^^^^^^^^^^
The method onMenuItemClickListener(String, (<no type> item) -> {}) is undefined for the type DropDownView

* I'm use java and I get this error , any solution please .

**Comment by qandeelabbassi** [comment]
@DanielHerzz it's setItemClickListener not onMenuItemClickListener

**Comment by DanielHerzz** [comment]
Send the correct code for the java

**Comment by qandeelabbassi** [comment]
Try this:
```java
dropdown_fruits.setItemClickListener((position, item) -> {
    Toast.makeText(this, "${item.text} clicked at index $i", Toast.LENGTH_SHORT).show();
});
```
